env:
  node: true
  commonjs: true
  es6: true
  browser: true
parserOptions:
  ecmaVersion: 8
  sourceType: module
  ecmaFeatures:
    jsx: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - never
  no-console: 0
  no-unused-vars:
    - 2
    - varsIgnorePattern: "^_"
      argsIgnorePattern: "^_"
  no-ignore: 0
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
